name: Go

on:
  push:
    branches: [ main, kalee, donghyki, jiychoi ]
  pull_request:
    branches: [ main ]

jobs:
  
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2

    - name: Set up Go
      uses: actions/setup-go@v2
      with:
        go-version: 1.17
        
    - name: Set up GoLint
      run: go install golang.org/x/lint/golint@latest
        
    - name: Lint
      run: golint ./...

    - name: Test
      run: go test -v ./...
